### ISSUE TITLE
Guia de instalação

### ISSUE THREAD

**Issue by samverneck** [Webschool-io/vuejs-2-na-pratica#2]
Acho valido colocar o passo a passo de instalação do vue.
Abraço

**Comment by IgorHalfeld** [comment]
@samverneck você quer dizer, configurar o Vue com alguma ferramenta (ex. webpack, browserify, gulp....)?

**Comment by ednilsonamaral** [comment]
Uma apostila, aqui no repositório. Estaremos providênciando :)

**Comment by samverneck** [comment]
@Halfeld Uma apostila como o @ednilsonamaral disse.

**Comment by ednilsonamaral** [comment]
@samverneck guia de instalação disponível! :smile:

**Comment by samverneck** [comment]
show de bola @ednilsonamaral valeu!
