### ISSUE TITLE
Exercícios 1-4

### ISSUE THREAD

**Issue by Marlysson** [Webschool-io/vuejs-2-na-pratica#8]
Só há os exercícios 5 e 6 ..

**Comment by IgorHalfeld** [comment]
Na aula 07, eu falei no video, mas já coloco no repositório

**Comment by ednilsonamaral** [comment]
Já está aqui no repositório o que é para fazer como [exercício da aula 07](https://github.com/Webschool-io/vuejs-2-na-pratica/tree/master/Exercicios/aula07), @Marlysson.
